application:
  title: Ecommerce API Service
  version: v1.0

logging:
  level:
    ROOT: INFO

# Server Configuration
server:
  port: 8080
  host: localhost
  servlet:
    context-path: /ecommerce

# Spring Configurations
spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:h2:mem:ecommerce-h2-database
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      minimumIdle: 5
      maximumPoolSize: 50
      connectionTimeout: 2000
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-update
        jdbc:
          lob:
            non_contextual_creation: false
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true

# OpenAPI Configurations
openapi:
  title: Ecommerce API Service
  version: v1.0
  description: Ecommerce API service
  termsOfService:
  contact:
    email:
    name:
    url:
  license:
    name:
    url:

# Default Open API endpoint Specifications
# api docs endpoint path
springdoc:
  api-docs.path: /v3/api-docs
  # customise endpoint for Swagger UI
  swagger-ui:
    path: /swagger-ui
    # disable default petstore Swagger
    disable-swagger-default-url: true
    # disable schemas/models in swagger ui
    defaultModelsExpandDepth=-1:

#web-config-origin-url
web:
  config:
    allowed-origin-urls:
      http://localhost:3000,
      http://localhost:3001,
      http://localhost:3002,
    max-age: 3600

